spring.application.name=receitafaker

spring.threads.virtual.enabled=true
server.port=${PORT:8080}
spring.jackson.time-zone=${APP_TIMEZONE:America/Sao_Paulo}

spring.mongodb.uri=${MONGO_URI:mongodb://root:developer@localhost:27017/datafaker?authSource=admin&connectTimeoutMS=5000&socketTimeoutMS=10000&serverSelectionTimeoutMS=5000&maxPoolSize=20&minPoolSize=10}
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# SpringDoc OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
